version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "friday"
    # Labels on pull requests for security and version updates
    target-branch: "dev"
    # Labels on pull requests for version updates only
