name: Team Awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "APPROVED"
        REMOVE_LABEL: "awaiting%20review"
