name: Lint CloudFormation Templates

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -i W3011,E3030,E3041,E3503 -t ./template.yaml
